// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANen9ZqqxMG8wmtz6Ss_ZNiGCBTUweWUw',
    appId: '1:358886432630:web:9868ca650479cf965f6457',
    messagingSenderId: '358886432630',
    projectId: 'stackmodetest',
    authDomain: 'stackmodetest.firebaseapp.com',
    storageBucket: 'stackmodetest.firebasestorage.app',
    measurementId: 'G-F9LH8TNQVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq42buYu4pqQbxi4w0tdRm8c8iHtyetxA',
    appId: '1:358886432630:android:40e92b108d51f90e5f6457',
    messagingSenderId: '358886432630',
    projectId: 'stackmodetest',
    storageBucket: 'stackmodetest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTjqbKQONI3EfHb1TPNA6kdGQBmfQBCL8',
    appId: '1:358886432630:ios:71dd3e4057d25d3f5f6457',
    messagingSenderId: '358886432630',
    projectId: 'stackmodetest',
    storageBucket: 'stackmodetest.firebasestorage.app',
    iosBundleId: 'com.example.stackmodetest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTjqbKQONI3EfHb1TPNA6kdGQBmfQBCL8',
    appId: '1:358886432630:ios:71dd3e4057d25d3f5f6457',
    messagingSenderId: '358886432630',
    projectId: 'stackmodetest',
    storageBucket: 'stackmodetest.firebasestorage.app',
    iosBundleId: 'com.example.stackmodetest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANen9ZqqxMG8wmtz6Ss_ZNiGCBTUweWUw',
    appId: '1:358886432630:web:1eae9b18225e63f45f6457',
    messagingSenderId: '358886432630',
    projectId: 'stackmodetest',
    authDomain: 'stackmodetest.firebaseapp.com',
    storageBucket: 'stackmodetest.firebasestorage.app',
    measurementId: 'G-8C8NBYZ3D1',
  );
}
